version: '3.7'

services:
  mysql-server:
    image: mysql:latest
    container_name: personal-project-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password123
    expose:
      - "3306"
    ports:
      - "3312:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: personal-project-phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-server
      PMA_PORT: 3306  # Corrected the port
      PMA_USER: root
      PMA_PASSWORD: password123
    ports:
      - "8345:80"
    depends_on:
      - mysql-server
